### ISSUE TITLE
TFE: green screen after demo

### ISSUE THREAD

**Issue by legluondunet** [tx00100xt/SeriousSamClassic-VK#19]
Hello,
when SeriousSam TFE launches, I press a key to bypass logos and intros, then it starts a demo. If I do nothing,  at the end of demo, I have only a green screen , if I wait nothing else happen, I have to press a key to return to menu.
I don't think it is a normal behavior.
At the end of the demo, if user does nothing, there should be another demo starting, doesn't it?

**Comment by legluondunet** [comment]
My config:
OS: Manjaro 22.0.5 Sikaris
Kernel: x86_64 Linux 6.2.7-2-MANJARO
CPU: AMD Ryzen 9 5900HX with Radeon Graphics @ 16x 3.3GHz
GPU: AMD Radeon RX 6600M (navi23, LLVM 15.0.7, DRM 3.49, 6.2.7-2-MANJARO)
Video drivers: Mesa 22.3.5

SeriousSamClassicVk-1.10.4-lnx-glibc-2.36-amd64-bin.tar.xz

**Comment by tx00100xt** [comment]
If you run the version for Windows, CD Gold or GOG, then we will see the same thing there. Because the demos were recorded in version 1.00 of the engine and are played in version 1.05. The engines themselves version 1.00 1.05 1.07 and 1.10 are incompatible with each other. That's why we see such an effect when a demo was recorded on one version of the engine and played back on another.

To interrupt intro and demo I use <ESC>. Since there is still partial compatibility, you can click the left mouse button to change the demo, before the end of the demo. Then the next demo will start playing.

**Comment by legluondunet** [comment]
ok thank you for the explanation.
