### ISSUE TITLE
Mods dont work. serious sam tfe complains about missing .so files 

### ISSUE THREAD

**Issue by LethalManBoob** [tx00100xt/SeriousSamClassic-VK#25]
it wants some .so files in /usr/lib/serioussam/ ive also noticed mods in that file and they cant be loaded now

**Comment by tx00100xt** [comment]
I rewrote all PKGBUIDs so that they are located according to the standard.
https://bbs.archlinux.org/viewtopic.php?pid=2102727#p2102727

Here is a detailed description of how all files should be located
https://github.com/tx00100xt/SeriousSamClassic-VK/wiki/How-to-building-a-package-for-Debian-or-Ubuntu.md

Need to update both game and mods.

**Comment by LethalManBoob** [comment]
[SeriousSam.log](https://github.com/tx00100xt/SeriousSamClassic-VK/files/11627751/SeriousSam.log)
uninstalled, deleted everything, install from scratch, got this

**Comment by tx00100xt** [comment]
Here with the log we can immediately see all the problems.
1st problem:
>Assumed mods library directory: /usr/lib/x86_64-linux-gnu/serioussam/
>
I thought that x86_64-linux-gnu directory is not used in arch linux.
2nd problem:
The game itself found the game data in:
>Assumed engine data directory: /home/joseph/.local/share/Steam/steamapps/common/Serious Sam Classic The First >Encounter/

and set it as the default directory. And mod data is located in /usr/share/serioussan/Mods.
Will have to think again.

**Comment by tx00100xt** [comment]
I came up with a solution - will update soon

**Comment by tx00100xt** [comment]
Ready
https://aur.archlinux.org/cgit/aur.git/log/?h=serioussam
https://aur.archlinux.org/cgit/aur.git/log/?h=serioussam-vk

**Installation order**
1. Delete directories (if they exist):
>/usr/share/serioussam/SamTFE
>/usr/share/serioussam/SamTSE
>
2. You need to install a new version of the game 1.10.4-8
3. Then install mods.
4. Delete files (if they exist):
>~/.local/share/Serious-Engine/serioussam/SeriousSam.cfg
>~/.local/share/Serious-Engine/serioussamse/SeriousSam.cfg
>
5. Copy:
- Help (folder)
- Levels (folder)
- 1_00_ExtraTools.gro
- 1_00_music.gro
- 1_00c.gro
 - 1_00c_scripts.gro
- 1_04_patch.gro
from /home/joseph/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter/
to /usr/share/serioussam/
6. Copy:
 - Help (folder)
- SE1_00.gro
- SE1_00_Extra.gro
- SE1_00_ExtraTools.gro
- SE1_00_Levels.gro
- SE1_00.gro
- SE1_00_Music.gro
- 1_04_patch.gro
- 1_07_patch.gro
from /home/joseph/.local/share/Steam/steamapps/common/Serious Sam Classic The Second Encounter/
to /usr/share/serioussamse/
7. Now you can start the game

Everything should work now

**Comment by LethalManBoob** [comment]
serious sam launches now but mods dont show up

**Comment by tx00100xt** [comment]
> serious sam launches now but mods dont show up

You need to delete these files:
> ~/.local/share/Serious-Engine/serioussam/SeriousSam.cfg
> ~/.local/share/Serious-Engine/serioussamse/SeriousSam.cfg

These files contain the found path to the data.
Just remove them before starting the game.


I think this line is in the log again
>Assumed engine data directory: /home/joseph/.local/share/Steam/steamapps/common/Serious Sam Classic The First >Encounter/

Please attach the game log.

**Comment by LethalManBoob** [comment]
[SeriousSam.log](https://github.com/tx00100xt/SeriousSamClassic-VK/files/11642216/SeriousSam.log)
Still can not load mods. As i saw a patch today.

**Comment by tx00100xt** [comment]
> [SeriousSam.log](https://github.com/tx00100xt/SeriousSamClassic-VK/files/11642216/SeriousSam.log) Still can not load mods. As i saw a patch today.

In LOG
>Running 64-bit version
Testing home path: /home/joseph/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter/
Testing file: 1_00_music.gro
Found path: /home/joseph/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter/
Executable: /usr/bin/
Assumed engine data directory: /home/joseph/.local/share/Steam/steamapps/common/Serious Sam Classic The First Encounter/
Assumed mods library directory: /usr/lib64/serioussam/

Should be like this
>Running 64-bit version
Testing file: 1_00_music.gro
Testing system path: /usr/share/serioussam/1_00_music.gro
Testing local  path: /home/tx00100xt/.local/share/Serious-Engine/serioussam/1_00_music.gro
Found usr path: 
Executable: /usr/bin/
Assumed engine data directory: /usr/share/serioussam/
Assumed mods library directory: /usr/lib64/serioussam/


It's because you didn't delete the file:
## SeriousSam.cfg
Open the console and run the commands:
`rm -vf /home/joseph/.local/share/Serious-Engine/serioussam/SeriousSam.cfg`
`rm -vf /home/joseph/.local/share/Serious-Engine/serioussamse/SeriousSam.cfg`

After that, start the game again.
Mods should appear in the menu.
The log should change to look like this:
>Running 64-bit version
Testing file: 1_00_music.gro
Testing system path: /usr/share/serioussam/1_00_music.gro
Testing local  path: /home/joseph/.local/share/Serious-Engine/serioussam/1_00_music.gro
Found usr path: 
Executable: /usr/bin/
Assumed engine data directory: /usr/share/serioussam/
Assumed mods library directory: /usr/lib64/serioussam/

And the question - do you have a symlink in the system? (**/usr** directory):
**lib64 --> lib**

**Comment by LethalManBoob** [comment]
yes i have the symlink lib64 to lib. Deleted files and rebooted
[SeriousSam.log](https://github.com/tx00100xt/SeriousSamClassic-VK/files/11642695/SeriousSam.log)

**Comment by tx00100xt** [comment]
in log:
>Running 64-bit version
Testing file: 1_00_music.gro
Testing system path: /usr/share/serioussam/1_00_music.gro
Testing local  path: /home/joseph/.local/share/Serious-Engine/serioussam/1_00_music.gro
**No game files were found in /usr/share/serioussam/**
 or /home/joseph/.local/share/Serious-Engine/serioussam/
The home directory will be searched.

**You forgot to copy the game data to the directories:**
`/usr/share/serioussam/`
`/usr/share/serioussamse/`

Open the console and run the commands (again):
`rm -vf /home/joseph/.local/share/Serious-Engine/serioussam/SeriousSam.cfg`
`rm -vf /home/joseph/.local/share/Serious-Engine/serioussamse/SeriousSam.cfg`
And copy the game files to these directories:
 Copy:
- Help (folder)
- Levels (folder)
- 1_00_ExtraTools.gro
- 1_00_music.gro
- 1_00c.gro
- 1_00c_scripts.gro
- 1_04_patch.gro
to /usr/share/serioussam/
 Copy:
- Help (folder)
- SE1_00.gro
- SE1_00_Extra.gro
- SE1_00_ExtraTools.gro
- SE1_00_Levels.gro
- SE1_00.gro
- SE1_00_Music.gro
- 1_04_patch.gro
- 1_07_patch.gro
to /usr/share/serioussamse/

**Comment by LethalManBoob** [comment]
it works now ;v

**Comment by tx00100xt** [comment]
Great.
You can also delete the old data location.
Open the console and run the commands (again):
`sudo rm -vfr  /usr/share/serioussam/SamTFE`
`sudo rm -vfr  /usr/share/serioussam/SamTSE`

**Comment by tx00100xt** [comment]
Since not everyone needs modifications, I removed the XPLUS modification from packages serioussam and serioussam-vk. Now there is a separate package https://aur.archlinux.org/packages/serioussam-xplus for this modification. I think this will be correct.
Now the build time for packages serioussam and serioussam-vk has been reduced, and the size of the packages received for installation has also been reduced.

**Comment by tx00100xt** [comment]
> it works now ;v

Since everything works and the problem is solved, I think the issue can be closed.
