### ISSUE TITLE
Support MacOS ?

### ISSUE THREAD

**Issue by Heic0** [tx00100xt/SeriousSamClassic-VK#26]
I building it on MacOS and it`s work. But I have small moving textures on weapons. How fix it ? I think it a timer !
You can see my git https://github.com/tx00100xt/SeriousSamClassic-VK/compare/main...Heic0:SeriousSamClassic-VK:main

**Comment by tx00100xt** [comment]
Yes, although MacOS is not in the readme, it should actually work.
Since the game runs on FreeBSD, and MacOS is used to build under FreeBSD on Github Action.
https://github.com/tx00100xt/SeriousSamClassic-VK/actions/runs/5158328130

> But I have small moving textures on weapons. How fix it ?
>
I also had this on my weapon. It has to do with the game settings. You need to change mdl_bFineQuality = 0 to mdl_bFineQuality = 1 everywhere in the scripts Scripts/GLSettings/RAM.ini and Scripts/GLSettings/ATI-RPRO.ini
When using sed and bash, you can give commands:
`cd SeriousSamClassic-VK `
`find . -name "RAM.ini" -exec sed -i 's/mdl_bFineQuality = 0;/mdl_bFineQuality = 1;/g' {} +`
`find . -name "ATI-RPRO.ini" -exec sed -i 's/mdl_bFineQuality = 0;/mdl_bFineQuality = 1;/g' {} +`

**Comment by tx00100xt** [comment]
I looked at the commits in: https://github.com/tx00100xt/SeriousSamClassic-VK/compare/main...Heic0:SeriousSamClassic-VK:main

Added 5:4 aspect ratio and 8k resolution:
https://github.com/tx00100xt/SeriousSamClassic/commit/bd1fda1d42bff5f52d79fc829acd9943c8dba438
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/ca87908caff01e19a21c49a164f7ea85ab08c367

**Comment by Heic0** [comment]
Thanks you for add commit. Apple system can to be support future, also your not have planned ?

**Comment by tx00100xt** [comment]
Added:
https://github.com/tx00100xt/SeriousSamClassic/commit/14b50e41addee3385b2c615d5cdd02fd726dc564
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/28a5a5ebe6d1d3a8b30553d0459096695e34d97a

https://github.com/tx00100xt/SeriousSamClassic/actions/runs/5169090816/jobs/9311134808
https://github.com/tx00100xt/SeriousSamClassic-VK/actions/runs/5168808370

You can download the resulting binaries after compilation here:
https://github.com/tx00100xt/SeriousSamClassic-VK/actions
https://github.com/tx00100xt/SeriousSamClassic-VK/actions/runs/5169429298

> But I have small moving textures on weapons. How fix it ?

Fixed:
https://github.com/tx00100xt/SeriousSamClassic/commit/35ea82471443d86fd3aa6343839916c993d58d83
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/f2e4085ae3512b4e499e58e9caa8d8c902360d65

**Comment by tx00100xt** [comment]
> Thanks you for add commit. Apple system can to be support future, also your not have planned ?

Added to Readme.md and description
https://github.com/tx00100xt/SeriousSamClassic#readme 
https://github.com/tx00100xt/SeriousSamClassic-VK#readme
